server:
  port: ${PORT:9999}
spring:
  rabbitmq:
    host: localhost
    username: admin
    password: admin
    virtual-host: v-phoenix
    port: 5672
  datasource:
    druid:
      url:
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 30
      min-idle: 3
      initial-size: 3
      validation-query: select 1
      max-wait: 5000
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        allow:
        deny:
        url-pattern:
          - /druid/*
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
management:
  endpoints:
    web:
      exposure:
        include: '*'  #暴露健康检查端点，让服务可被监控


